// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b3fa472f-cf3b-470d-a5e5-6841fdc4caf4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDc1Change();
void onDc2Change();
void onKdAChange();
void onKdBChange();
void onKiAChange();
void onKiBChange();
void onKpAChange();
void onKpBChange();
void onS1Change();
void onS2Change();
void onS3Change();
void onSwitchChange();

float currentAngle1;
float currentAngle2;
float dc1;
float dc2;
float kdA;
float kdB;
float kiA;
float kiB;
float kpA;
float kpB;
int pWMA;
int pWMB;
int s1;
int s2;
int s3;
bool limit_switch_state;
bool limit_switch_state1;
bool _switch_;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(currentAngle1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(currentAngle2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dc1, READWRITE, ON_CHANGE, onDc1Change);
  ArduinoCloud.addProperty(dc2, READWRITE, ON_CHANGE, onDc2Change);
  ArduinoCloud.addProperty(kdA, READWRITE, ON_CHANGE, onKdAChange);
  ArduinoCloud.addProperty(kdB, READWRITE, ON_CHANGE, onKdBChange);
  ArduinoCloud.addProperty(kiA, READWRITE, ON_CHANGE, onKiAChange);
  ArduinoCloud.addProperty(kiB, READWRITE, ON_CHANGE, onKiBChange);
  ArduinoCloud.addProperty(kpA, READWRITE, ON_CHANGE, onKpAChange);
  ArduinoCloud.addProperty(kpB, READWRITE, ON_CHANGE, onKpBChange);
  ArduinoCloud.addProperty(pWMA, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pWMB, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(s1, READWRITE, ON_CHANGE, onS1Change, 180);
  ArduinoCloud.addProperty(s2, READWRITE, ON_CHANGE, onS2Change, 180);
  ArduinoCloud.addProperty(s3, READWRITE, ON_CHANGE, onS3Change, 180);
  ArduinoCloud.addProperty(limit_switch_state, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(limit_switch_state1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(_switch_, READWRITE, ON_CHANGE, onSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
